source 'https://rubygems.org'

gem 'cucumber', '~> 3.1.0'
gem 'capybara'
gem 'selenium-webdriver'
gem 'rspec'
gem 'capybara-screenshot'
gem 'json'                        
gem 'cucumber-api', '~> 0.9'      
gem 'report_builder', '~> 1.9'