source 'https://rubygems.org'

gem 'cucumber'
gem 'capybara'
gem 'selenium-webdriver'
gem 'rspec'
gem 'capybara-screenshot'
gem 'cucumber-reporting', '~> 6.0'  
gem 'json'                        
gem 'cucumber-api'      
gem 'report_builder', '~> 1.9'